version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./avito-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
